from fastapi import APIRouter
router = APIRouter()
from .Ind140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia import router as Ind140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia_router
router.include_router(Ind140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia_router, prefix='/Ind140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind020SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica import router as Ind020SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica_router
router.include_router(Ind020SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica_router, prefix='/Ind020SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind260anexoiiDeclaraciónResponsablePorLaEmpresa import router as Ind260anexoiiDeclaraciónResponsablePorLaEmpresa_router
router.include_router(Ind260anexoiiDeclaraciónResponsablePorLaEmpresa_router, prefix='/Ind260anexoiiDeclaraciónResponsablePorLaEmpresa', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind040anexovDocumentaciónTécnica import router as Ind040anexovDocumentaciónTécnica_router
router.include_router(Ind040anexovDocumentaciónTécnica_router, prefix='/Ind040anexovDocumentaciónTécnica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind220anexoiiValoresDeReferenciaDeLaFórmula import router as Ind220anexoiiValoresDeReferenciaDeLaFórmula_router
router.include_router(Ind220anexoiiValoresDeReferenciaDeLaFórmula_router, prefix='/Ind220anexoiiValoresDeReferenciaDeLaFórmula', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas import router as Ind120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas_router
router.include_router(Ind120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas_router, prefix='/Ind120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind060anexovDocumentaciónTécnica import router as Ind060anexovDocumentaciónTécnica_router
router.include_router(Ind060anexovDocumentaciónTécnica_router, prefix='/Ind060anexovDocumentaciónTécnica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind190anexoiiValoresDeReferenciaDeLaFormula import router as Ind190anexoiiValoresDeReferenciaDeLaFormula_router
router.include_router(Ind190anexoiiValoresDeReferenciaDeLaFormula_router, prefix='/Ind190anexoiiValoresDeReferenciaDeLaFormula', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind210anexoiiValoresDeReferenciaDeLaFórmula import router as Ind210anexoiiValoresDeReferenciaDeLaFórmula_router
router.include_router(Ind210anexoiiValoresDeReferenciaDeLaFórmula_router, prefix='/Ind210anexoiiValoresDeReferenciaDeLaFórmula', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind050SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed import router as Ind050SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed_router
router.include_router(Ind050SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed_router, prefix='/Ind050SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind030anexoiiTablas import router as Ind030anexoiiTablas_router
router.include_router(Ind030anexoiiTablas_router, prefix='/Ind030anexoiiTablas', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind010anexoivPérdidasTérmicasObjetivoDeAcuerdoCon import router as Ind010anexoivPérdidasTérmicasObjetivoDeAcuerdoCon_router
router.include_router(Ind010anexoivPérdidasTérmicasObjetivoDeAcuerdoCon_router, prefix='/Ind010anexoivPérdidasTérmicasObjetivoDeAcuerdoCon', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind150anexoiiValoresDeReferenciaDeLaFórmula import router as Ind150anexoiiValoresDeReferenciaDeLaFórmula_router
router.include_router(Ind150anexoiiValoresDeReferenciaDeLaFórmula_router, prefix='/Ind150anexoiiValoresDeReferenciaDeLaFórmula', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind230anexoiiInformeJustificativoDeLosEquiposQueCeden import router as Ind230anexoiiInformeJustificativoDeLosEquiposQueCeden_router
router.include_router(Ind230anexoiiInformeJustificativoDeLosEquiposQueCeden_router, prefix='/Ind230anexoiiInformeJustificativoDeLosEquiposQueCeden', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind190DivisiónDeLíneasDeEvaporaciónEnInstalaciónFrigoríficaCentralizada import router as Ind190DivisiónDeLíneasDeEvaporaciónEnInstalaciónFrigoríficaCentralizada_router
router.include_router(Ind190DivisiónDeLíneasDeEvaporaciónEnInstalaciónFrigoríficaCentralizada_router, prefix='/Ind190DivisiónDeLíneasDeEvaporaciónEnInstalaciónFrigoríficaCentralizada', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind040anexoiiiDemandaAnualDeEnergíaParaAcs import router as Ind040anexoiiiDemandaAnualDeEnergíaParaAcs_router
router.include_router(Ind040anexoiiiDemandaAnualDeEnergíaParaAcs_router, prefix='/Ind040anexoiiiDemandaAnualDeEnergíaParaAcs', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind150anexoiiiInformeJustificativoDeLaCentralFrigorífica import router as Ind150anexoiiiInformeJustificativoDeLaCentralFrigorífica_router
router.include_router(Ind150anexoiiiInformeJustificativoDeLaCentralFrigorífica_router, prefix='/Ind150anexoiiiInformeJustificativoDeLaCentralFrigorífica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind150CentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta import router as Ind150CentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta_router
router.include_router(Ind150CentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta_router, prefix='/Ind150CentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind270SustituciónDeTransporteNeumáticoDeSólidosPorSistemaDeTransporteMecánico import router as Ind270SustituciónDeTransporteNeumáticoDeSólidosPorSistemaDeTransporteMecánico_router
router.include_router(Ind270SustituciónDeTransporteNeumáticoDeSólidosPorSistemaDeTransporteMecánico_router, prefix='/Ind270SustituciónDeTransporteNeumáticoDeSólidosPorSistemaDeTransporteMecánico', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind010anexovPérdidasTérmicasParaEscenarioBaseDe import router as Ind010anexovPérdidasTérmicasParaEscenarioBaseDe_router
router.include_router(Ind010anexovPérdidasTérmicasParaEscenarioBaseDe_router, prefix='/Ind010anexovPérdidasTérmicasParaEscenarioBaseDe', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind170SustituciónDeMotoresEléctricosDeInducción import router as Ind170SustituciónDeMotoresEléctricosDeInducción_router
router.include_router(Ind170SustituciónDeMotoresEléctricosDeInducción_router, prefix='/Ind170SustituciónDeMotoresEléctricosDeInducción', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind010anexoiiiCertificadoDeLaCorrectaRealizaciónDeLa import router as Ind010anexoiiiCertificadoDeLaCorrectaRealizaciónDeLa_router
router.include_router(Ind010anexoiiiCertificadoDeLaCorrectaRealizaciónDeLa_router, prefix='/Ind010anexoiiiCertificadoDeLaCorrectaRealizaciónDeLa', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind220AumentoDeLaPresiónDeEvaporaciónPorCambioATecnologíaMásEficienteEnUnaInstalaciónFrigoríficaCentralizadaOCompacta import router as Ind220AumentoDeLaPresiónDeEvaporaciónPorCambioATecnologíaMásEficienteEnUnaInstalaciónFrigoríficaCentralizadaOCompacta_router
router.include_router(Ind220AumentoDeLaPresiónDeEvaporaciónPorCambioATecnologíaMásEficienteEnUnaInstalaciónFrigoríficaCentralizadaOCompacta_router, prefix='/Ind220AumentoDeLaPresiónDeEvaporaciónPorCambioATecnologíaMásEficienteEnUnaInstalaciónFrigoríficaCentralizadaOCompacta', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind081SustituciónDelRecuperadorCámaraIsobáricaOIntercambiadorDePresiónCip import router as Ind081SustituciónDelRecuperadorCámaraIsobáricaOIntercambiadorDePresiónCip_router
router.include_router(Ind081SustituciónDelRecuperadorCámaraIsobáricaOIntercambiadorDePresiónCip_router, prefix='/Ind081SustituciónDelRecuperadorCámaraIsobáricaOIntercambiadorDePresiónCip', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind020anexoiiiNotaInformativaAcercaDeLaSustituciónDe import router as Ind020anexoiiiNotaInformativaAcercaDeLaSustituciónDe_router
router.include_router(Ind020anexoiiiNotaInformativaAcercaDeLaSustituciónDe_router, prefix='/Ind020anexoiiiNotaInformativaAcercaDeLaSustituciónDe', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind080InstalaciónDeUnaCámaraIsobáricaOIntercambiadorDePresiónCip import router as Ind080InstalaciónDeUnaCámaraIsobáricaOIntercambiadorDePresiónCip_router
router.include_router(Ind080InstalaciónDeUnaCámaraIsobáricaOIntercambiadorDePresiónCip_router, prefix='/Ind080InstalaciónDeUnaCámaraIsobáricaOIntercambiadorDePresiónCip', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind090anexoiiInformeJustificativoDeLaDemandaDeAire import router as Ind090anexoiiInformeJustificativoDeLaDemandaDeAire_router
router.include_router(Ind090anexoiiInformeJustificativoDeLaDemandaDeAire_router, prefix='/Ind090anexoiiInformeJustificativoDeLaDemandaDeAire', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind240ImplantaciónDeVariadorDeVelocidad import router as Ind240ImplantaciónDeVariadorDeVelocidad_router
router.include_router(Ind240ImplantaciónDeVariadorDeVelocidad_router, prefix='/Ind240ImplantaciónDeVariadorDeVelocidad', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind140anexoiiValoresDeReferenciaDeLaFórmula import router as Ind140anexoiiValoresDeReferenciaDeLaFórmula_router
router.include_router(Ind140anexoiiValoresDeReferenciaDeLaFórmula_router, prefix='/Ind140anexoiiValoresDeReferenciaDeLaFórmula', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind040SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalor import router as Ind040SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalor_router
router.include_router(Ind040SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalor_router, prefix='/Ind040SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalor', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind060anexoivFórmulasParaObtenerLosCoeficientesDe import router as Ind060anexoivFórmulasParaObtenerLosCoeficientesDe_router
router.include_router(Ind060anexoivFórmulasParaObtenerLosCoeficientesDe_router, prefix='/Ind060anexoivFórmulasParaObtenerLosCoeficientesDe', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind040anexoivRendimientoDeCalderaSustituida import router as Ind040anexoivRendimientoDeCalderaSustituida_router
router.include_router(Ind040anexoivRendimientoDeCalderaSustituida_router, prefix='/Ind040anexoivRendimientoDeCalderaSustituida', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind020anexoiiTablas import router as Ind020anexoiiTablas_router
router.include_router(Ind020anexoiiTablas_router, prefix='/Ind020anexoiiTablas', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind070SustituciónDeBombaDeAltaPresiónPorUnaBombaDePistonesAxiales import router as Ind070SustituciónDeBombaDeAltaPresiónPorUnaBombaDePistonesAxiales_router
router.include_router(Ind070SustituciónDeBombaDeAltaPresiónPorUnaBombaDePistonesAxiales_router, prefix='/Ind070SustituciónDeBombaDeAltaPresiónPorUnaBombaDePistonesAxiales', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind180MejoraDeEficienciaOSustituciónDeIntercambiadorEsDeCalorParaLaReducciónDeLaResistividadTérmicaEnSistemasIndustriales import router as Ind180MejoraDeEficienciaOSustituciónDeIntercambiadorEsDeCalorParaLaReducciónDeLaResistividadTérmicaEnSistemasIndustriales_router
router.include_router(Ind180MejoraDeEficienciaOSustituciónDeIntercambiadorEsDeCalorParaLaReducciónDeLaResistividadTérmicaEnSistemasIndustriales_router, prefix='/Ind180MejoraDeEficienciaOSustituciónDeIntercambiadorEsDeCalorParaLaReducciónDeLaResistividadTérmicaEnSistemasIndustriales', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind160UnidadCondensadoraDeAltaEficiencia import router as Ind160UnidadCondensadoraDeAltaEficiencia_router
router.include_router(Ind160UnidadCondensadoraDeAltaEficiencia_router, prefix='/Ind160UnidadCondensadoraDeAltaEficiencia', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai import router as Ind260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai_router
router.include_router(Ind260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai_router, prefix='/Ind260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind290RecuperaciónDeCalorEnCircuitoFrigorífico import router as Ind290RecuperaciónDeCalorEnCircuitoFrigorífico_router
router.include_router(Ind290RecuperaciónDeCalorEnCircuitoFrigorífico_router, prefix='/Ind290RecuperaciónDeCalorEnCircuitoFrigorífico', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind200ImplantaciónDeSistemasEconomizadoresOMultietapaEnInstalaciónFrigoríficaCentralizadaOCompacta import router as Ind200ImplantaciónDeSistemasEconomizadoresOMultietapaEnInstalaciónFrigoríficaCentralizadaOCompacta_router
router.include_router(Ind200ImplantaciónDeSistemasEconomizadoresOMultietapaEnInstalaciónFrigoríficaCentralizadaOCompacta_router, prefix='/Ind200ImplantaciónDeSistemasEconomizadoresOMultietapaEnInstalaciónFrigoríficaCentralizadaOCompacta', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind090SustituciónOReemplazoDeCompresorDeAirePorUnoMásEficiente import router as Ind090SustituciónOReemplazoDeCompresorDeAirePorUnoMásEficiente_router
router.include_router(Ind090SustituciónOReemplazoDeCompresorDeAirePorUnoMásEficiente_router, prefix='/Ind090SustituciónOReemplazoDeCompresorDeAirePorUnoMásEficiente', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind010MejoraDelAislamientoDeTuberíasYSuperficiesPlanasDeInstalacionesYEquiposUtilizadosEnProcesosIndustrialesParaTemperaturasDeMásDe60 import router as Ind010MejoraDelAislamientoDeTuberíasYSuperficiesPlanasDeInstalacionesYEquiposUtilizadosEnProcesosIndustrialesParaTemperaturasDeMásDe60_router
router.include_router(Ind010MejoraDelAislamientoDeTuberíasYSuperficiesPlanasDeInstalacionesYEquiposUtilizadosEnProcesosIndustrialesParaTemperaturasDeMásDe60_router, prefix='/Ind010MejoraDelAislamientoDeTuberíasYSuperficiesPlanasDeInstalacionesYEquiposUtilizadosEnProcesosIndustrialesParaTemperaturasDeMásDe60', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind190anexoiiiInformeJustificativoDeLaCentralFrigorífica import router as Ind190anexoiiiInformeJustificativoDeLaCentralFrigorífica_router
router.include_router(Ind190anexoiiiInformeJustificativoDeLaCentralFrigorífica_router, prefix='/Ind190anexoiiiInformeJustificativoDeLaCentralFrigorífica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind040anexoiiDeclaraciónFórmulasParaRealizarLa import router as Ind040anexoiiDeclaraciónFórmulasParaRealizarLa_router
router.include_router(Ind040anexoiiDeclaraciónFórmulasParaRealizarLa_router, prefix='/Ind040anexoiiDeclaraciónFórmulasParaRealizarLa', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind060anexoiiCálculoDelRendimientoEstacionalDeEquipos import router as Ind060anexoiiCálculoDelRendimientoEstacionalDeEquipos_router
router.include_router(Ind060anexoiiCálculoDelRendimientoEstacionalDeEquipos_router, prefix='/Ind060anexoiiCálculoDelRendimientoEstacionalDeEquipos', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind220anexoiiiInformeJustificativoDeLaCentralFrigorífica import router as Ind220anexoiiiInformeJustificativoDeLaCentralFrigorífica_router
router.include_router(Ind220anexoiiiInformeJustificativoDeLaCentralFrigorífica_router, prefix='/Ind220anexoiiiInformeJustificativoDeLaCentralFrigorífica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind050anexoiiTiempoAnualDeFuncionamientoDelSistemaDe import router as Ind050anexoiiTiempoAnualDeFuncionamientoDelSistemaDe_router
router.include_router(Ind050anexoiiTiempoAnualDeFuncionamientoDelSistemaDe_router, prefix='/Ind050anexoiiTiempoAnualDeFuncionamientoDelSistemaDe', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind030SustituciónDeCompresorParaInstalaciónFrigorífica import router as Ind030SustituciónDeCompresorParaInstalaciónFrigorífica_router
router.include_router(Ind030SustituciónDeCompresorParaInstalaciónFrigorífica_router, prefix='/Ind030SustituciónDeCompresorParaInstalaciónFrigorífica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind060anexoiiiEquivalenciasClimasCteZonasClimáticas import router as Ind060anexoiiiEquivalenciasClimasCteZonasClimáticas_router
router.include_router(Ind060anexoiiiEquivalenciasClimasCteZonasClimáticas_router, prefix='/Ind060anexoiiiEquivalenciasClimasCteZonasClimáticas', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind010anexoiiInformeJustificativoDeLaInstalaciónObjetoDe import router as Ind010anexoiiInformeJustificativoDeLaInstalaciónObjetoDe_router
router.include_router(Ind010anexoiiInformeJustificativoDeLaInstalaciónObjetoDe_router, prefix='/Ind010anexoiiInformeJustificativoDeLaInstalaciónObjetoDe', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind280SustituciónDeBombaPorOtraMásEficiente import router as Ind280SustituciónDeBombaPorOtraMásEficiente_router
router.include_router(Ind280SustituciónDeBombaPorOtraMásEficiente_router, prefix='/Ind280SustituciónDeBombaPorOtraMásEficiente', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind230RecuperaciónDeCalorDesdeProcesosExotérmicosAOtrosProcesosEndotérmicosDeLaMismaPlanta import router as Ind230RecuperaciónDeCalorDesdeProcesosExotérmicosAOtrosProcesosEndotérmicosDeLaMismaPlanta_router
router.include_router(Ind230RecuperaciónDeCalorDesdeProcesosExotérmicosAOtrosProcesosEndotérmicosDeLaMismaPlanta_router, prefix='/Ind230RecuperaciónDeCalorDesdeProcesosExotérmicosAOtrosProcesosEndotérmicosDeLaMismaPlanta', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind160anexoiiiInformeJustificativoDeLaCentralFrigorífica import router as Ind160anexoiiiInformeJustificativoDeLaCentralFrigorífica_router
router.include_router(Ind160anexoiiiInformeJustificativoDeLaCentralFrigorífica_router, prefix='/Ind160anexoiiiInformeJustificativoDeLaCentralFrigorífica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind160anexoiiValoresDeReferenciaDeLaFórmula import router as Ind160anexoiiValoresDeReferenciaDeLaFórmula_router
router.include_router(Ind160anexoiiValoresDeReferenciaDeLaFórmula_router, prefix='/Ind160anexoiiValoresDeReferenciaDeLaFórmula', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind210anexoiiiInformeJustificativoDeLaCentralFrigorífica import router as Ind210anexoiiiInformeJustificativoDeLaCentralFrigorífica_router
router.include_router(Ind210anexoiiiInformeJustificativoDeLaCentralFrigorífica_router, prefix='/Ind210anexoiiiInformeJustificativoDeLaCentralFrigorífica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind060SustituciónDeGeneradorParaClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico import router as Ind060SustituciónDeGeneradorParaClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico_router
router.include_router(Ind060SustituciónDeGeneradorParaClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico_router, prefix='/Ind060SustituciónDeGeneradorParaClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind280anexoiiCálculoDelRendimientoTotalDeLaBomba import router as Ind280anexoiiCálculoDelRendimientoTotalDeLaBomba_router
router.include_router(Ind280anexoiiCálculoDelRendimientoTotalDeLaBomba_router, prefix='/Ind280anexoiiCálculoDelRendimientoTotalDeLaBomba', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind110RecuperaciónDeCalorDeUnCompresorParaUsoDeCalefacción import router as Ind110RecuperaciónDeCalorDeUnCompresorParaUsoDeCalefacción_router
router.include_router(Ind110RecuperaciónDeCalorDeUnCompresorParaUsoDeCalefacción_router, prefix='/Ind110RecuperaciónDeCalorDeUnCompresorParaUsoDeCalefacción', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind250SustituciónTotalOParcialDeLaInstalaciónTérmicaPorTecnologíaSolarTérmica import router as Ind250SustituciónTotalOParcialDeLaInstalaciónTérmicaPorTecnologíaSolarTérmica_router
router.include_router(Ind250SustituciónTotalOParcialDeLaInstalaciónTérmicaPorTecnologíaSolarTérmica_router, prefix='/Ind250SustituciónTotalOParcialDeLaInstalaciónTérmicaPorTecnologíaSolarTérmica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind210ReducciónDeLaPresiónDeCondensaciónEnInstalaciónFrigoríficaCentralizadaOCompactaPorCambioATecnologíaMásEficiente import router as Ind210ReducciónDeLaPresiónDeCondensaciónEnInstalaciónFrigoríficaCentralizadaOCompactaPorCambioATecnologíaMásEficiente_router
router.include_router(Ind210ReducciónDeLaPresiónDeCondensaciónEnInstalaciónFrigoríficaCentralizadaOCompactaPorCambioATecnologíaMásEficiente_router, prefix='/Ind210ReducciónDeLaPresiónDeCondensaciónEnInstalaciónFrigoríficaCentralizadaOCompactaPorCambioATecnologíaMásEficiente', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind200anexoiiValoresDeReferenciaDeLaFórmula import router as Ind200anexoiiValoresDeReferenciaDeLaFórmula_router
router.include_router(Ind200anexoiiValoresDeReferenciaDeLaFórmula_router, prefix='/Ind200anexoiiValoresDeReferenciaDeLaFórmula', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
from .Ind140anexoiiiInformeJustificativoDeLaCentralFrigorífica import router as Ind140anexoiiiInformeJustificativoDeLaCentralFrigorífica_router
router.include_router(Ind140anexoiiiInformeJustificativoDeLaCentralFrigorífica_router, prefix='/Ind140anexoiiiInformeJustificativoDeLaCentralFrigorífica', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Industrial'])
