from fastapi import APIRouter
router = APIRouter()
from .Tra030anexoiiRequisitosParaLaAplicaciónDeLaFicha import router as Tra030anexoiiRequisitosParaLaAplicaciónDeLaFicha_router
router.include_router(Tra030anexoiiRequisitosParaLaAplicaciónDeLaFicha_router, prefix='/Tra030anexoiiRequisitosParaLaAplicaciónDeLaFicha', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra040anexoiiRequisitosParaLaAplicaciónDeLaFicha import router as Tra040anexoiiRequisitosParaLaAplicaciónDeLaFicha_router
router.include_router(Tra040anexoiiRequisitosParaLaAplicaciónDeLaFicha_router, prefix='/Tra040anexoiiRequisitosParaLaAplicaciónDeLaFicha', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra040anexoiiiCriteriosAntifraudeParaLaCorrecta import router as Tra040anexoiiiCriteriosAntifraudeParaLaCorrecta_router
router.include_router(Tra040anexoiiiCriteriosAntifraudeParaLaCorrecta_router, prefix='/Tra040anexoiiiCriteriosAntifraudeParaLaCorrecta', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra010anexoiDeclaraciónResponsableFormalizadaPorEl import router as Tra010anexoiDeclaraciónResponsableFormalizadaPorEl_router
router.include_router(Tra010anexoiDeclaraciónResponsableFormalizadaPorEl_router, prefix='/Tra010anexoiDeclaraciónResponsableFormalizadaPorEl', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra020anexoiiRequerimientosTécnicosDeLaSoluciónTelemática import router as Tra020anexoiiRequerimientosTécnicosDeLaSoluciónTelemática_router
router.include_router(Tra020anexoiiRequerimientosTécnicosDeLaSoluciónTelemática_router, prefix='/Tra020anexoiiRequerimientosTécnicosDeLaSoluciónTelemática', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra030anexoiiiCriteriosAntifraudeParaLaCorrecta import router as Tra030anexoiiiCriteriosAntifraudeParaLaCorrecta_router
router.include_router(Tra030anexoiiiCriteriosAntifraudeParaLaCorrecta_router, prefix='/Tra030anexoiiiCriteriosAntifraudeParaLaCorrecta', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra050anexoiiiKilometrosRealizadosSegúnLaTipologíaDel import router as Tra050anexoiiiKilometrosRealizadosSegúnLaTipologíaDel_router
router.include_router(Tra050anexoiiiKilometrosRealizadosSegúnLaTipologíaDel_router, prefix='/Tra050anexoiiiKilometrosRealizadosSegúnLaTipologíaDel', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra010anexoiiAhorroEnergéticoPorSustituciónDeNeumático import router as Tra010anexoiiAhorroEnergéticoPorSustituciónDeNeumático_router
router.include_router(Tra010anexoiiAhorroEnergéticoPorSustituciónDeNeumático_router, prefix='/Tra010anexoiiAhorroEnergéticoPorSustituciónDeNeumático', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra030VehículoCompartidoEnTrayectosDeLargoRecorrido import router as Tra030VehículoCompartidoEnTrayectosDeLargoRecorrido_router
router.include_router(Tra030VehículoCompartidoEnTrayectosDeLargoRecorrido_router, prefix='/Tra030VehículoCompartidoEnTrayectosDeLargoRecorrido', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra050anexoiiMétodosParaObtenerLosConsumosDeVehículos import router as Tra050anexoiiMétodosParaObtenerLosConsumosDeVehículos_router
router.include_router(Tra050anexoiiMétodosParaObtenerLosConsumosDeVehículos_router, prefix='/Tra050anexoiiMétodosParaObtenerLosConsumosDeVehículos', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra050anexoiDeclaraciónResponsableFormalizadaPorEl import router as Tra050anexoiDeclaraciónResponsableFormalizadaPorEl_router
router.include_router(Tra050anexoiDeclaraciónResponsableFormalizadaPorEl_router, prefix='/Tra050anexoiDeclaraciónResponsableFormalizadaPorEl', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra040anexoiDeclaraciónResponsableFormalizadaPorEl import router as Tra040anexoiDeclaraciónResponsableFormalizadaPorEl_router
router.include_router(Tra040anexoiDeclaraciónResponsableFormalizadaPorEl_router, prefix='/Tra040anexoiDeclaraciónResponsableFormalizadaPorEl', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra010anexoiiiKilometrosRealizadosSegúnLaTipologíaDel import router as Tra010anexoiiiKilometrosRealizadosSegúnLaTipologíaDel_router
router.include_router(Tra010anexoiiiKilometrosRealizadosSegúnLaTipologíaDel_router, prefix='/Tra010anexoiiiKilometrosRealizadosSegúnLaTipologíaDel', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra040MovilidadColaborativaUrbanaYMetropolitana import router as Tra040MovilidadColaborativaUrbanaYMetropolitana_router
router.include_router(Tra040MovilidadColaborativaUrbanaYMetropolitana_router, prefix='/Tra040MovilidadColaborativaUrbanaYMetropolitana', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
from .Tra050SustituciónDeVehículoDeCombustiónPorUnVehículoEléctricoPuro import router as Tra050SustituciónDeVehículoDeCombustiónPorUnVehículoEléctricoPuro_router
router.include_router(Tra050SustituciónDeVehículoDeCombustiónPorUnVehículoEléctricoPuro_router, prefix='/Tra050SustituciónDeVehículoDeCombustiónPorUnVehículoEléctricoPuro', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Transporte'])
