import Cer1001TérminoDeFacturaciónDeEnergíaActivaDelPvpc20td from './docs/CONTRATOS_DE_ENERGÍA/Mercado_regulado/Cer1001TérminoDeFacturaciónDeEnergíaActivaDelPvpc20td.jsx';
import Cer1739PrecioDeLaEnergíaExcedentariaDelAutoconsumo from './docs/CONTRATOS_DE_ENERGÍA/Mercado_regulado/Cer1739PrecioDeLaEnergíaExcedentariaDelAutoconsumo.jsx';
import Acaf000AnálisisFinanciero from './docs/ENERGÍA_FOTOVOLTAICA/Comun/Acaf000AnálisisFinanciero.jsx';
import Acpvpc00PreciosPvpc from './docs/ENERGÍA_FOTOVOLTAICA/Comun/Acpvpc00PreciosPvpc.jsx';
import Afc020AutoconsumoColectivoConExcedentesYConCompensaciónConectadaEnRedInterior from './docs/ENERGÍA_FOTOVOLTAICA/Individual/Afc020AutoconsumoColectivoConExcedentesYConCompensaciónConectadaEnRedInterior.jsx';
import Aif030AnálisisDeOfertaDeAutoconsumo from './docs/ENERGÍA_FOTOVOLTAICA/Individual/Aif030AnálisisDeOfertaDeAutoconsumo.jsx';
import Aif040GeneracionFotovoltaica from './docs/ENERGÍA_FOTOVOLTAICA/Individual/Aif040GeneracionFotovoltaica.jsx';
import Bt040401InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónBásico from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT0_Memoria_Técnica_De_Diseño/Bt040401InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónBásico.jsx';
import Bt040402InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónElevado from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT0_Memoria_Técnica_De_Diseño/Bt040402InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónElevado.jsx';
import Bt100PrevisiónDeCargasParaSuministrosEnBajaTensión from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT1_Instalaciones_De_Enlace/Bt100PrevisiónDeCargasParaSuministrosEnBajaTensión.jsx';
import Bt220ProtecciónContraSobreintensidades from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT6_Protecciones/Bt220ProtecciónContraSobreintensidades.jsx';
import Bt240ProtecciónContraContactosIndirectos from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT6_Protecciones/Bt240ProtecciónContraContactosIndirectos.jsx';
import Bt400InstalacionesGeneradorasDeBajaTensión from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT7_Instalaciones_Especiales/Bt400InstalacionesGeneradorasDeBajaTensión.jsx';
import Bt520InfraestructuraParaLaRecargaDeVehículosEléctricos from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT7_Instalaciones_Especiales/Bt520InfraestructuraParaLaRecargaDeVehículosEléctricos.jsx';
import Btx030BateríaDeCondensadores from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT9_Otras_Instalaciones/Btx030BateríaDeCondensadores.jsx';
import Btx040FiltroDeArmónicos from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT9_Otras_Instalaciones/Btx040FiltroDeArmónicos.jsx';
import Btx047InstalaciónDeComunicaciónDeSaiLegrand from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT9_Otras_Instalaciones/Btx047InstalaciónDeComunicaciónDeSaiLegrand.jsx';
import Btx060SistemaDeAlimentaciónIninterrumpidaSai from './docs/INSTALACIONES_ELÉCTRICAS_BT/RBT9_Otras_Instalaciones/Btx060SistemaDeAlimentaciónIninterrumpidaSai.jsx';

const componentsMap = {
  Cer1001TérminoDeFacturaciónDeEnergíaActivaDelPvpc20td,
  Cer1739PrecioDeLaEnergíaExcedentariaDelAutoconsumo,
  Acaf000AnálisisFinanciero,
  Acpvpc00PreciosPvpc,
  Afc020AutoconsumoColectivoConExcedentesYConCompensaciónConectadaEnRedInterior,
  Aif030AnálisisDeOfertaDeAutoconsumo,
  Aif040GeneracionFotovoltaica,
  Bt040401InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónBásico,
  Bt040402InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónElevado,
  Bt100PrevisiónDeCargasParaSuministrosEnBajaTensión,
  Bt220ProtecciónContraSobreintensidades,
  Bt240ProtecciónContraContactosIndirectos,
  Bt400InstalacionesGeneradorasDeBajaTensión,
  Bt520InfraestructuraParaLaRecargaDeVehículosEléctricos,
  Btx030BateríaDeCondensadores,
  Btx040FiltroDeArmónicos,
  Btx047InstalaciónDeComunicaciónDeSaiLegrand,
  Btx060SistemaDeAlimentaciónIninterrumpidaSai,
};

export default componentsMap;
