import Agr010PantallasTérmicasEnInvernaderos from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Agrario/Agr010PantallasTérmicasEnInvernaderos.jsx';
import Agr010anexoiiiDeclaraciónResponsableDelValorDel from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Agrario/Agr010anexoiiiDeclaraciónResponsableDelValorDel.jsx';
import Agr020RecuperaciónDelCalorDelProcesoDePreenfriamientoDeLaLecheParaUsosTérmicosEnLaExplotaciónGanadera from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Agrario/Agr020RecuperaciónDelCalorDelProcesoDePreenfriamientoDeLaLecheParaUsosTérmicosEnLaExplotaciónGanadera.jsx';
import SecretariaDeEstadoDeEnergíaMinisterioDirecciónGeneralDePlanificaciónYParaLaTransiciónEcológicaYElRetoDemográficoCoordinaciónEnergéticaTra020SistemaDeTelemetríaYGeoposicionamientoEnFlotaDeTransporte from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Catálogo_Vigente/SecretariaDeEstadoDeEnergíaMinisterioDirecciónGeneralDePlanificaciónYParaLaTransiciónEcológicaYElRetoDemográficoCoordinaciónEnergéticaTra020SistemaDeTelemetríaYGeoposicionamientoEnFlotaDeTransporte.jsx';
import Ind010MejoraDelAislamientoDeTuberíasYSuperficiesPlanasDeInstalacionesYEquiposUtilizadosEnProcesosIndustrialesParaTemperaturasDeMásDe60 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind010MejoraDelAislamientoDeTuberíasYSuperficiesPlanasDeInstalacionesYEquiposUtilizadosEnProcesosIndustrialesParaTemperaturasDeMásDe60.jsx';
import Ind010anexoiiInformeJustificativoDeLaInstalaciónObjetoDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind010anexoiiInformeJustificativoDeLaInstalaciónObjetoDe.jsx';
import Ind010anexoiiiCertificadoDeLaCorrectaRealizaciónDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind010anexoiiiCertificadoDeLaCorrectaRealizaciónDeLa.jsx';
import Ind010anexoivPérdidasTérmicasObjetivoDeAcuerdoCon from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind010anexoivPérdidasTérmicasObjetivoDeAcuerdoCon.jsx';
import Ind010anexovPérdidasTérmicasParaEscenarioBaseDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind010anexovPérdidasTérmicasParaEscenarioBaseDe.jsx';
import Ind020SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind020SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica.jsx';
import Ind020anexoiiTablas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind020anexoiiTablas.jsx';
import Ind020anexoiiiNotaInformativaAcercaDeLaSustituciónDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind020anexoiiiNotaInformativaAcercaDeLaSustituciónDe.jsx';
import Ind030SustituciónDeCompresorParaInstalaciónFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind030SustituciónDeCompresorParaInstalaciónFrigorífica.jsx';
import Ind030anexoiiTablas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind030anexoiiTablas.jsx';
import Ind040SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalor from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind040SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalor.jsx';
import Ind040anexoiiDeclaraciónFórmulasParaRealizarLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind040anexoiiDeclaraciónFórmulasParaRealizarLa.jsx';
import Ind040anexoiiiDemandaAnualDeEnergíaParaAcs from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind040anexoiiiDemandaAnualDeEnergíaParaAcs.jsx';
import Ind040anexoivRendimientoDeCalderaSustituida from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind040anexoivRendimientoDeCalderaSustituida.jsx';
import Ind040anexovDocumentaciónTécnica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind040anexovDocumentaciónTécnica.jsx';
import Ind050SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind050SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed.jsx';
import Ind050anexoiiTiempoAnualDeFuncionamientoDelSistemaDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind050anexoiiTiempoAnualDeFuncionamientoDelSistemaDe.jsx';
import Ind060SustituciónDeGeneradorParaClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind060SustituciónDeGeneradorParaClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico.jsx';
import Ind060anexoiiCálculoDelRendimientoEstacionalDeEquipos from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind060anexoiiCálculoDelRendimientoEstacionalDeEquipos.jsx';
import Ind060anexoiiiEquivalenciasClimasCteZonasClimáticas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind060anexoiiiEquivalenciasClimasCteZonasClimáticas.jsx';
import Ind060anexoivFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind060anexoivFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ind060anexovDocumentaciónTécnica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind060anexovDocumentaciónTécnica.jsx';
import Ind070SustituciónDeBombaDeAltaPresiónPorUnaBombaDePistonesAxiales from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind070SustituciónDeBombaDeAltaPresiónPorUnaBombaDePistonesAxiales.jsx';
import Ind080InstalaciónDeUnaCámaraIsobáricaOIntercambiadorDePresiónCip from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind080InstalaciónDeUnaCámaraIsobáricaOIntercambiadorDePresiónCip.jsx';
import Ind081SustituciónDelRecuperadorCámaraIsobáricaOIntercambiadorDePresiónCip from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind081SustituciónDelRecuperadorCámaraIsobáricaOIntercambiadorDePresiónCip.jsx';
import Ind090SustituciónOReemplazoDeCompresorDeAirePorUnoMásEficiente from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind090SustituciónOReemplazoDeCompresorDeAirePorUnoMásEficiente.jsx';
import Ind090anexoiiInformeJustificativoDeLaDemandaDeAire from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind090anexoiiInformeJustificativoDeLaDemandaDeAire.jsx';
import Ind110RecuperaciónDeCalorDeUnCompresorParaUsoDeCalefacción from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind110RecuperaciónDeCalorDeUnCompresorParaUsoDeCalefacción.jsx';
import Ind120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas.jsx';
import Ind140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia.jsx';
import Ind140anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind140anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ind140anexoiiiInformeJustificativoDeLaCentralFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind140anexoiiiInformeJustificativoDeLaCentralFrigorífica.jsx';
import Ind150CentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind150CentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta.jsx';
import Ind150anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind150anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ind150anexoiiiInformeJustificativoDeLaCentralFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind150anexoiiiInformeJustificativoDeLaCentralFrigorífica.jsx';
import Ind160UnidadCondensadoraDeAltaEficiencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind160UnidadCondensadoraDeAltaEficiencia.jsx';
import Ind160anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind160anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ind160anexoiiiInformeJustificativoDeLaCentralFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind160anexoiiiInformeJustificativoDeLaCentralFrigorífica.jsx';
import Ind170SustituciónDeMotoresEléctricosDeInducción from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind170SustituciónDeMotoresEléctricosDeInducción.jsx';
import Ind180MejoraDeEficienciaOSustituciónDeIntercambiadorEsDeCalorParaLaReducciónDeLaResistividadTérmicaEnSistemasIndustriales from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind180MejoraDeEficienciaOSustituciónDeIntercambiadorEsDeCalorParaLaReducciónDeLaResistividadTérmicaEnSistemasIndustriales.jsx';
import Ind190DivisiónDeLíneasDeEvaporaciónEnInstalaciónFrigoríficaCentralizada from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind190DivisiónDeLíneasDeEvaporaciónEnInstalaciónFrigoríficaCentralizada.jsx';
import Ind190anexoiiValoresDeReferenciaDeLaFormula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind190anexoiiValoresDeReferenciaDeLaFormula.jsx';
import Ind190anexoiiiInformeJustificativoDeLaCentralFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind190anexoiiiInformeJustificativoDeLaCentralFrigorífica.jsx';
import Ind200ImplantaciónDeSistemasEconomizadoresOMultietapaEnInstalaciónFrigoríficaCentralizadaOCompacta from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind200ImplantaciónDeSistemasEconomizadoresOMultietapaEnInstalaciónFrigoríficaCentralizadaOCompacta.jsx';
import Ind200anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind200anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ind210ReducciónDeLaPresiónDeCondensaciónEnInstalaciónFrigoríficaCentralizadaOCompactaPorCambioATecnologíaMásEficiente from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind210ReducciónDeLaPresiónDeCondensaciónEnInstalaciónFrigoríficaCentralizadaOCompactaPorCambioATecnologíaMásEficiente.jsx';
import Ind210anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind210anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ind210anexoiiiInformeJustificativoDeLaCentralFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind210anexoiiiInformeJustificativoDeLaCentralFrigorífica.jsx';
import Ind220AumentoDeLaPresiónDeEvaporaciónPorCambioATecnologíaMásEficienteEnUnaInstalaciónFrigoríficaCentralizadaOCompacta from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind220AumentoDeLaPresiónDeEvaporaciónPorCambioATecnologíaMásEficienteEnUnaInstalaciónFrigoríficaCentralizadaOCompacta.jsx';
import Ind220anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind220anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ind220anexoiiiInformeJustificativoDeLaCentralFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind220anexoiiiInformeJustificativoDeLaCentralFrigorífica.jsx';
import Ind230RecuperaciónDeCalorDesdeProcesosExotérmicosAOtrosProcesosEndotérmicosDeLaMismaPlanta from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind230RecuperaciónDeCalorDesdeProcesosExotérmicosAOtrosProcesosEndotérmicosDeLaMismaPlanta.jsx';
import Ind230anexoiiInformeJustificativoDeLosEquiposQueCeden from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind230anexoiiInformeJustificativoDeLosEquiposQueCeden.jsx';
import Ind240ImplantaciónDeVariadorDeVelocidad from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind240ImplantaciónDeVariadorDeVelocidad.jsx';
import Ind250SustituciónTotalOParcialDeLaInstalaciónTérmicaPorTecnologíaSolarTérmica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind250SustituciónTotalOParcialDeLaInstalaciónTérmicaPorTecnologíaSolarTérmica.jsx';
import Ind260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai.jsx';
import Ind260anexoiiDeclaraciónResponsablePorLaEmpresa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind260anexoiiDeclaraciónResponsablePorLaEmpresa.jsx';
import Ind270SustituciónDeTransporteNeumáticoDeSólidosPorSistemaDeTransporteMecánico from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind270SustituciónDeTransporteNeumáticoDeSólidosPorSistemaDeTransporteMecánico.jsx';
import Ind280SustituciónDeBombaPorOtraMásEficiente from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind280SustituciónDeBombaPorOtraMásEficiente.jsx';
import Ind280anexoiiCálculoDelRendimientoTotalDeLaBomba from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind280anexoiiCálculoDelRendimientoTotalDeLaBomba.jsx';
import Ind290RecuperaciónDeCalorEnCircuitoFrigorífico from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Industrial/Ind290RecuperaciónDeCalorEnCircuitoFrigorífico.jsx';
import Res010RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaMayorDel25PorCiento from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res010RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaMayorDel25PorCiento.jsx';
import Res010anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res010anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Res011RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaMayorDel25PorCientoCanarias from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res011RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaMayorDel25PorCientoCanarias.jsx';
import Res011anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res011anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Res020RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaInferiorOIgualAl25PorCientoDeLaEnvolventeTérmicaFinal from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res020RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaInferiorOIgualAl25PorCientoDeLaEnvolventeTérmicaFinal.jsx';
import Res020anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res020anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Res021RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaInferiorOIgualAl25PorCientoDeLaEnvolventeTérmicaFinalCanarias from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res021RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaInferiorOIgualAl25PorCientoDeLaEnvolventeTérmicaFinalCanarias.jsx';
import Res021anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res021anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Res030NuevaImplantaciónSustituciónOAmpliaciónDeInstalaciónTérmicaEnUnEdificioYPiscinaConTecnologíaSolarTérmica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res030NuevaImplantaciónSustituciónOAmpliaciónDeInstalaciónTérmicaEnUnEdificioYPiscinaConTecnologíaSolarTérmica.jsx';
import Res040SistemaDeAutomatizaciónYControlParaViviendasYEdificiosBacs1 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res040SistemaDeAutomatizaciónYControlParaViviendasYEdificiosBacs1.jsx';
import Res040anexoii1TablaDeFactoresDeEficienciaParaEdificios from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res040anexoii1TablaDeFactoresDeEficienciaParaEdificios.jsx';
import Res040anexoiiiDeclaraciónResponsableDeLaEvaluaciónDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res040anexoiiiDeclaraciónResponsableDeLaEvaluaciónDeLa.jsx';
import Res050AdquisiciónDeFrigoríficosDeAltaEficiencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res050AdquisiciónDeFrigoríficosDeAltaEficiencia.jsx';
import Res050anexoiiTablasConValoresDeReferenciaConsumosDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res050anexoiiTablasConValoresDeReferenciaConsumosDe.jsx';
import Res051AdquisiciónDeFrigoríficocongeladorDeAltaEficiencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res051AdquisiciónDeFrigoríficocongeladorDeAltaEficiencia.jsx';
import Res051anexoiiTablasConValoresDeReferenciaConsumosDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res051anexoiiTablasConValoresDeReferenciaConsumosDe.jsx';
import Res052AdquisiciónDeCongeladorDeAltaEficiencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res052AdquisiciónDeCongeladorDeAltaEficiencia.jsx';
import Res052anexoiiTablasConValoresDeReferenciaConsumosDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res052anexoiiTablasConValoresDeReferenciaConsumosDe.jsx';
import Res053AdquisiciónDeLavadorasDeAltaEficiencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res053AdquisiciónDeLavadorasDeAltaEficiencia.jsx';
import Res053anexoiiTablasConValoresDeReferenciaConsumosDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res053anexoiiTablasConValoresDeReferenciaConsumosDe.jsx';
import Res054AdquisiciónDeLavavajillasDeAltaEficiencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res054AdquisiciónDeLavavajillasDeAltaEficiencia.jsx';
import Res054anexoiiTablasConValoresDeReferenciaConsumosDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res054anexoiiTablasConValoresDeReferenciaConsumosDe.jsx';
import Res060SustituciónDeCalderaDeCombustiónPorUnaBombaDeCalorDeAccionamientoEléctrico from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res060SustituciónDeCalderaDeCombustiónPorUnaBombaDeCalorDeAccionamientoEléctrico.jsx';
import Res060anexoiiCasosDondeLaCalderaDeCombustiónSeMantiene from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res060anexoiiCasosDondeLaCalderaDeCombustiónSeMantiene.jsx';
import Res060anexoiiiEquivalenciasClimasCteYZonasClimáticas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res060anexoiiiEquivalenciasClimasCteYZonasClimáticas.jsx';
import Res060anexoivFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res060anexoivFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res060anexovDocumentaciónTécnica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res060anexovDocumentaciónTécnica.jsx';
import Res060anexoviCondicionesConsideradasEnAcs from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res060anexoviCondicionesConsideradasEnAcs.jsx';
import Res070RenovaciónOSustituciónDeVentanasEnEdificiosDeViviendas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res070RenovaciónOSustituciónDeVentanasEnEdificiosDeViviendas.jsx';
import Res070anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res070anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Res071RenovaciónOSustituciónDeVentanasEnEdificiosDeViviendasCanarias from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res071RenovaciónOSustituciónDeVentanasEnEdificiosDeViviendasCanarias.jsx';
import Res071anexoiiValoresDeCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res071anexoiiValoresDeCoeficienteGSegúnZonaClimática.jsx';
import Res080RehabilitaciónProfundaDeEdificiosDeViviendas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res080RehabilitaciónProfundaDeEdificiosDeViviendas.jsx';
import Res090HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaA3OA4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res090HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaA3OA4.jsx';
import Res090anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res090anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res090anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res090anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia.jsx';
import Res091HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaB3OB4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res091HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaB3OB4.jsx';
import Res091anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res091anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res091anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res091anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia.jsx';
import Res092HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaC1C2C3OC4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res092HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaC1C2C3OC4.jsx';
import Res092anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res092anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res092anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res092anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia.jsx';
import Res093HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaD1D2OD3 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res093HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaD1D2OD3.jsx';
import Res093anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res093anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res093anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res093anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia.jsx';
import Res094HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaE1 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res094HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaE1.jsx';
import Res094anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res094anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res094anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res094anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia.jsx';
import Res095HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaA3OA4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res095HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaA3OA4.jsx';
import Res095anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res095anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res095anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res095anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Res096anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res096anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res096anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res096anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Res097anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res097anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res097anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res097anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Res098anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res098anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res098anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res098anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Res099anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res099anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Res099anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res099anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Res210anexoiiRendimientoDeCalderaSustituida from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res210anexoiiRendimientoDeCalderaSustituida.jsx';
import Res220anexoiiFactoresParaElCálculoDelAhorroDeEnergía from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res220anexoiiFactoresParaElCálculoDelAhorroDeEnergía.jsx';
import Res230anexoiiFactoresParaElCálculoDelAhorroDeEnergía from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Residencial/Res230anexoiiFactoresParaElCálculoDelAhorroDeEnergía.jsx';
import Ter010RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosTerciariosExistentesConSuperficieAfectadaMayorDel25PorCiento from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter010RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosTerciariosExistentesConSuperficieAfectadaMayorDel25PorCiento.jsx';
import Ter010anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter010anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Ter011RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosTerciariosExistentesConSuperficieAfectadaMayorDel25PorCientoCanarias from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter011RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosTerciariosExistentesConSuperficieAfectadaMayorDel25PorCientoCanarias.jsx';
import Ter011anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter011anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Ter020RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosTerciariosConSuperficieAfectadaInferiorOIgualDel25PorCientoDeLaEnvolventeTérmicaFinal from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter020RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosTerciariosConSuperficieAfectadaInferiorOIgualDel25PorCientoDeLaEnvolventeTérmicaFinal.jsx';
import Ter020anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter020anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Ter021RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosTerciariosConSuperficieAfectadaInferiorOIgualDel25PorCientoDeLaEnvolventeTérmicaFinalCanarias from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter021RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosTerciariosConSuperficieAfectadaInferiorOIgualDel25PorCientoDeLaEnvolventeTérmicaFinalCanarias.jsx';
import Ter021anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter021anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Ter030SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter030SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed.jsx';
import Ter030anexoiiTiempoAnualDeFuncionamientoDelSistemaDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter030anexoiiTiempoAnualDeFuncionamientoDelSistemaDe.jsx';
import Ter040SustituciónDeGeneradorDeClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter040SustituciónDeGeneradorDeClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico.jsx';
import Ter040anexoiiCálculoDelRendimientoEstacionalDeEquipos from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter040anexoiiCálculoDelRendimientoEstacionalDeEquipos.jsx';
import Ter040anexoiiiEquivalenciasClimasCteYZonasClimáticas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter040anexoiiiEquivalenciasClimasCteYZonasClimáticas.jsx';
import Ter040anexoivFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter040anexoivFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter040anexoixCondicionesDeTemperaturaExteriorMedia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter040anexoixCondicionesDeTemperaturaExteriorMedia.jsx';
import Ter040anexovDocumentaciónTécnica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter040anexovDocumentaciónTécnica.jsx';
import Ter040anexoviCálculoDeLaDemandaDeAcs from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter040anexoviCálculoDeLaDemandaDeAcs.jsx';
import Ter040anexoviiCondicionesConsideradasEnAcs from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter040anexoviiCondicionesConsideradasEnAcs.jsx';
import Ter040anexoviiiCondicionesGeneralesParaCálculoDel from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter040anexoviiiCondicionesGeneralesParaCálculoDel.jsx';
import Ter050SistemaDeAutomatizaciónYControlParaEdificiosDelSectorTerciarioBacs1 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter050SistemaDeAutomatizaciónYControlParaEdificiosDelSectorTerciarioBacs1.jsx';
import Ter050anexoii1TablaDeFactoresDeEficienciaParaEdificiosNo from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter050anexoii1TablaDeFactoresDeEficienciaParaEdificiosNo.jsx';
import Ter050anexoiiiDeclaraciónResponsableDeLaEvaluaciónDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter050anexoiiiDeclaraciónResponsableDeLaEvaluaciónDeLa.jsx';
import Ter060RenovaciónOSustituciónDeVentanasEnEdificiosTerciariosExistentes from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter060RenovaciónOSustituciónDeVentanasEnEdificiosTerciariosExistentes.jsx';
import Ter060anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter060anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Ter061RenovaciónOSustituciónDeVentanasEnEdificiosExistentesCanarias from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter061RenovaciónOSustituciónDeVentanasEnEdificiosExistentesCanarias.jsx';
import Ter061anexoiiValoresDelCoeficienteGSegúnZonaClimática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter061anexoiiValoresDelCoeficienteGSegúnZonaClimática.jsx';
import Ter070NuevaImplantaciónSustituciónOAmpliaciónDeInstalaciónTérmicaEnUnEdificioYPiscinaConTecnologíaSolarTérmica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter070NuevaImplantaciónSustituciónOAmpliaciónDeInstalaciónTérmicaEnUnEdificioYPiscinaConTecnologíaSolarTérmica.jsx';
import Ter080RehabilitaciónProfundaDeUnEdificioTerciarioExistente from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter080RehabilitaciónProfundaDeUnEdificioTerciarioExistente.jsx';
import Ter090SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter090SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica.jsx';
import Ter090anexoiiTablas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter090anexoiiTablas.jsx';
import Ter090anexoiiiNotaInformativaAcercaDeLaSustituciónDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter090anexoiiiNotaInformativaAcercaDeLaSustituciónDe.jsx';
import Ter100SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalorDeAccionamientoEléctrico from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter100SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalorDeAccionamientoEléctrico.jsx';
import Ter100anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter100anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter100anexoiiiDocumentaciónTécnica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter100anexoiiiDocumentaciónTécnica.jsx';
import Ter100anexoivCondicionesConsideradasEnAcs from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter100anexoivCondicionesConsideradasEnAcs.jsx';
import Ter100anexovCálculoDeLaDemandaDeAcs from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter100anexovCálculoDeLaDemandaDeAcs.jsx';
import Ter100anexoviCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter100anexoviCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter100anexoviiCondicionesDeTemperaturaExteriorMedia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter100anexoviiCondicionesDeTemperaturaExteriorMedia.jsx';
import Ter100anexoviiiRendimientoDeCalderaSustituida from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter100anexoviiiRendimientoDeCalderaSustituida.jsx';
import Ter110SustituciónDeCompresorParaInstalaciónFrigoríficaODeClimatización from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter110SustituciónDeCompresorParaInstalaciónFrigoríficaODeClimatización.jsx';
import Ter110anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter110anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ter120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas.jsx';
import Ter140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia.jsx';
import Ter140anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter140anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ter140anexoiiiInformeJustificativoDeLaCentralFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter140anexoiiiInformeJustificativoDeLaCentralFrigorífica.jsx';
import Ter150ReformaSustituciónONuevaInstalaciónDeCentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter150ReformaSustituciónONuevaInstalaciónDeCentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta.jsx';
import Ter150anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter150anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ter150anexoiiiInformeJustificativoDeLaCentralFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter150anexoiiiInformeJustificativoDeLaCentralFrigorífica.jsx';
import Ter160SustituciónReformaONuevaInstalaciónDeUnaUnidadCondensadoraDeAltaEficiencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter160SustituciónReformaONuevaInstalaciónDeUnaUnidadCondensadoraDeAltaEficiencia.jsx';
import Ter160anexoiiValoresDeReferenciaDeLaFórmula from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter160anexoiiValoresDeReferenciaDeLaFórmula.jsx';
import Ter160anexoiiiInformeJustificativoDeLaCentralFrigorífica from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter160anexoiiiInformeJustificativoDeLaCentralFrigorífica.jsx';
import Ter170HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaA3OA4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter170HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaA3OA4.jsx';
import Ter170anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter170anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter170anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter170anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter170anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter170anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia.jsx';
import Ter171HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaB3OB4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter171HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaB3OB4.jsx';
import Ter171anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter171anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter171anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter171anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter171anexoivTablaDeCoeficientes1DeCoberturaPor from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter171anexoivTablaDeCoeficientes1DeCoberturaPor.jsx';
import Ter172HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaC1C2C3OC4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter172HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaC1C2C3OC4.jsx';
import Ter172anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter172anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter172anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter172anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter172anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter172anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia.jsx';
import Ter173HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaD1D2OD3 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter173HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaD1D2OD3.jsx';
import Ter173anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter173anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter173anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter173anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter173anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter173anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia.jsx';
import Ter174HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaE1 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter174HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaE1.jsx';
import Ter174anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter174anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter174anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter174anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter174anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter174anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia.jsx';
import Ter175HibridaciónEnModoAlternativoDeCalderaDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaA3OA4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter175HibridaciónEnModoAlternativoDeCalderaDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaA3OA4.jsx';
import Ter175anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter175anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter175anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter175anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter175anexoivTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter175anexoivTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Ter176HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaB3OB4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter176HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaB3OB4.jsx';
import Ter176anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter176anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter176anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter176anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter176anexoivTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter176anexoivTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Ter177HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaC1C2C3OC4 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter177HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaC1C2C3OC4.jsx';
import Ter177anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter177anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter177anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter177anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter177anexoivTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter177anexoivTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Ter178HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaD1D2OD3 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter178HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaD1D2OD3.jsx';
import Ter178anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter178anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter178anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter178anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter178anexoivTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter178anexoivTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Ter179HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaE1 from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter179HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaE1.jsx';
import Ter179anexoiiFórmulasParaObtenerLosCoeficientesDe from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter179anexoiiFórmulasParaObtenerLosCoeficientesDe.jsx';
import Ter179anexoiiiCondicionesGeneralesParaCálculoDeLa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter179anexoiiiCondicionesGeneralesParaCálculoDeLa.jsx';
import Ter179anexoivTablaDeCoeficientesDeCoberturaPorBivalencia from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter179anexoivTablaDeCoeficientesDeCoberturaPorBivalencia.jsx';
import Ter180SustituciónDelSistemaDeIluminaciónVialAmbiental from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter180SustituciónDelSistemaDeIluminaciónVialAmbiental.jsx';
import Ter190ReformadoDeAparatosDeRefrigeraciónParaAlimentosYBebidasDeVentaDirecta from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter190ReformadoDeAparatosDeRefrigeraciónParaAlimentosYBebidasDeVentaDirecta.jsx';
import Ter190anexoiiCoeficientesDeAhorroC from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter190anexoiiCoeficientesDeAhorroC.jsx';
import Ter200SustituciónDeAparatoDeRefrigeraciónConFunciónDeVentaDirecta from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter200SustituciónDeAparatoDeRefrigeraciónConFunciónDeVentaDirecta.jsx';
import Ter210SustituciónDeCalderasIndividualesColectivaEnEdificioTerciarioPorConexiónAUnaRedDeCalor from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter210SustituciónDeCalderasIndividualesColectivaEnEdificioTerciarioPorConexiónAUnaRedDeCalor.jsx';
import Ter210anexoiiRendimientoDeCalderaSustituida from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter210anexoiiRendimientoDeCalderaSustituida.jsx';
import Ter220SustituciónDeUnSistemaDeVentilaciónExistenteNaturalOMecánicaPorUnSistemaDeVentilaciónMecánicaConRecuperaciónDeCalorDeAltaEficienciaEnEdificiosNoResidenciales from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter220SustituciónDeUnSistemaDeVentilaciónExistenteNaturalOMecánicaPorUnSistemaDeVentilaciónMecánicaConRecuperaciónDeCalorDeAltaEficienciaEnEdificiosNoResidenciales.jsx';
import Ter220anexoiiFactoresParaElCálculoDelAhorroDeEnergía from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter220anexoiiFactoresParaElCálculoDelAhorroDeEnergía.jsx';
import Ter240ImplantaciónDeVariadorDeVelocidad from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter240ImplantaciónDeVariadorDeVelocidad.jsx';
import Ter260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai.jsx';
import Ter260anexoiiDeclaraciónResponsablePorLaEmpresa from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter260anexoiiDeclaraciónResponsablePorLaEmpresa.jsx';
import Ter280SustituciónDeBombaPorOtraMásEficiente from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter280SustituciónDeBombaPorOtraMásEficiente.jsx';
import Ter280anexoiiCálculoDelRendimientoTotalDeLaBomba from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Terciario/Ter280anexoiiCálculoDelRendimientoTotalDeLaBomba.jsx';
import Tra010anexoiDeclaraciónResponsableFormalizadaPorEl from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra010anexoiDeclaraciónResponsableFormalizadaPorEl.jsx';
import Tra010anexoiiAhorroEnergéticoPorSustituciónDeNeumático from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra010anexoiiAhorroEnergéticoPorSustituciónDeNeumático.jsx';
import Tra010anexoiiiKilometrosRealizadosSegúnLaTipologíaDel from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra010anexoiiiKilometrosRealizadosSegúnLaTipologíaDel.jsx';
import Tra020anexoiiRequerimientosTécnicosDeLaSoluciónTelemática from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra020anexoiiRequerimientosTécnicosDeLaSoluciónTelemática.jsx';
import Tra030VehículoCompartidoEnTrayectosDeLargoRecorrido from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra030VehículoCompartidoEnTrayectosDeLargoRecorrido.jsx';
import Tra030anexoiiRequisitosParaLaAplicaciónDeLaFicha from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra030anexoiiRequisitosParaLaAplicaciónDeLaFicha.jsx';
import Tra030anexoiiiCriteriosAntifraudeParaLaCorrecta from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra030anexoiiiCriteriosAntifraudeParaLaCorrecta.jsx';
import Tra040MovilidadColaborativaUrbanaYMetropolitana from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra040MovilidadColaborativaUrbanaYMetropolitana.jsx';
import Tra040anexoiDeclaraciónResponsableFormalizadaPorEl from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra040anexoiDeclaraciónResponsableFormalizadaPorEl.jsx';
import Tra040anexoiiRequisitosParaLaAplicaciónDeLaFicha from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra040anexoiiRequisitosParaLaAplicaciónDeLaFicha.jsx';
import Tra040anexoiiiCriteriosAntifraudeParaLaCorrecta from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra040anexoiiiCriteriosAntifraudeParaLaCorrecta.jsx';
import Tra050SustituciónDeVehículoDeCombustiónPorUnVehículoEléctricoPuro from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra050SustituciónDeVehículoDeCombustiónPorUnVehículoEléctricoPuro.jsx';
import Tra050anexoiDeclaraciónResponsableFormalizadaPorEl from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra050anexoiDeclaraciónResponsableFormalizadaPorEl.jsx';
import Tra050anexoiiMétodosParaObtenerLosConsumosDeVehículos from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra050anexoiiMétodosParaObtenerLosConsumosDeVehículos.jsx';
import Tra050anexoiiiKilometrosRealizadosSegúnLaTipologíaDel from '../docs/CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE/Transporte/Tra050anexoiiiKilometrosRealizadosSegúnLaTipologíaDel.jsx';
import Cer1001TérminoDeFacturaciónDeEnergíaActivaDelPvpc20td from '../docs/CONTRATOS_DE_ENERGÍA/Mercado_regulado/Cer1001TérminoDeFacturaciónDeEnergíaActivaDelPvpc20td.jsx';
import Cer1739PrecioDeLaEnergíaExcedentariaDelAutoconsumo from '../docs/CONTRATOS_DE_ENERGÍA/Mercado_regulado/Cer1739PrecioDeLaEnergíaExcedentariaDelAutoconsumo.jsx';
import Acaf000AnálisisFinanciero from '../docs/ENERGÍA_FOTOVOLTAICA/Comun/Acaf000AnálisisFinanciero.jsx';
import Acpvpc00PreciosPvpc from '../docs/ENERGÍA_FOTOVOLTAICA/Comun/Acpvpc00PreciosPvpc.jsx';
import Afc020AutoconsumoColectivoConExcedentesYConCompensaciónConectadaEnRedInterior from '../docs/ENERGÍA_FOTOVOLTAICA/Individual/Afc020AutoconsumoColectivoConExcedentesYConCompensaciónConectadaEnRedInterior.jsx';
import Aif030AnálisisDeOfertaDeAutoconsumo from '../docs/ENERGÍA_FOTOVOLTAICA/Individual/Aif030AnálisisDeOfertaDeAutoconsumo.jsx';
import Aif040GeneracionFotovoltaica from '../docs/ENERGÍA_FOTOVOLTAICA/Individual/Aif040GeneracionFotovoltaica.jsx';
import Bt040401InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónBásico from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT0_Memoria_Técnica_De_Diseño/Bt040401InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónBásico.jsx';
import Bt040402InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónElevado from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT0_Memoria_Técnica_De_Diseño/Bt040402InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónElevado.jsx';
import Bt100PrevisiónDeCargasParaSuministrosEnBajaTensión from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT1_Instalaciones_De_Enlace/Bt100PrevisiónDeCargasParaSuministrosEnBajaTensión.jsx';
import Bt220ProtecciónContraSobreintensidades from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT6_Protecciones/Bt220ProtecciónContraSobreintensidades.jsx';
import Bt240ProtecciónContraContactosIndirectos from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT6_Protecciones/Bt240ProtecciónContraContactosIndirectos.jsx';
import Bt400InstalacionesGeneradorasDeBajaTensión from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT7_Instalaciones_Especiales/Bt400InstalacionesGeneradorasDeBajaTensión.jsx';
import Bt520InfraestructuraParaLaRecargaDeVehículosEléctricos from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT7_Instalaciones_Especiales/Bt520InfraestructuraParaLaRecargaDeVehículosEléctricos.jsx';
import Btx030BateríaDeCondensadores from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT9_Otras_Instalaciones/Btx030BateríaDeCondensadores.jsx';
import Btx040FiltroDeArmónicos from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT9_Otras_Instalaciones/Btx040FiltroDeArmónicos.jsx';
import Btx047InstalaciónDeComunicaciónDeSaiLegrand from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT9_Otras_Instalaciones/Btx047InstalaciónDeComunicaciónDeSaiLegrand.jsx';
import Btx060SistemaDeAlimentaciónIninterrumpidaSai from '../docs/INSTALACIONES_ELÉCTRICAS_BT/RBT9_Otras_Instalaciones/Btx060SistemaDeAlimentaciónIninterrumpidaSai.jsx';

const componentsMap = {
  Agr010PantallasTérmicasEnInvernaderos,
  Agr010anexoiiiDeclaraciónResponsableDelValorDel,
  Agr020RecuperaciónDelCalorDelProcesoDePreenfriamientoDeLaLecheParaUsosTérmicosEnLaExplotaciónGanadera,
  SecretariaDeEstadoDeEnergíaMinisterioDirecciónGeneralDePlanificaciónYParaLaTransiciónEcológicaYElRetoDemográficoCoordinaciónEnergéticaTra020SistemaDeTelemetríaYGeoposicionamientoEnFlotaDeTransporte,
  Ind010MejoraDelAislamientoDeTuberíasYSuperficiesPlanasDeInstalacionesYEquiposUtilizadosEnProcesosIndustrialesParaTemperaturasDeMásDe60,
  Ind010anexoiiInformeJustificativoDeLaInstalaciónObjetoDe,
  Ind010anexoiiiCertificadoDeLaCorrectaRealizaciónDeLa,
  Ind010anexoivPérdidasTérmicasObjetivoDeAcuerdoCon,
  Ind010anexovPérdidasTérmicasParaEscenarioBaseDe,
  Ind020SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica,
  Ind020anexoiiTablas,
  Ind020anexoiiiNotaInformativaAcercaDeLaSustituciónDe,
  Ind030SustituciónDeCompresorParaInstalaciónFrigorífica,
  Ind030anexoiiTablas,
  Ind040SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalor,
  Ind040anexoiiDeclaraciónFórmulasParaRealizarLa,
  Ind040anexoiiiDemandaAnualDeEnergíaParaAcs,
  Ind040anexoivRendimientoDeCalderaSustituida,
  Ind040anexovDocumentaciónTécnica,
  Ind050SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed,
  Ind050anexoiiTiempoAnualDeFuncionamientoDelSistemaDe,
  Ind060SustituciónDeGeneradorParaClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico,
  Ind060anexoiiCálculoDelRendimientoEstacionalDeEquipos,
  Ind060anexoiiiEquivalenciasClimasCteZonasClimáticas,
  Ind060anexoivFórmulasParaObtenerLosCoeficientesDe,
  Ind060anexovDocumentaciónTécnica,
  Ind070SustituciónDeBombaDeAltaPresiónPorUnaBombaDePistonesAxiales,
  Ind080InstalaciónDeUnaCámaraIsobáricaOIntercambiadorDePresiónCip,
  Ind081SustituciónDelRecuperadorCámaraIsobáricaOIntercambiadorDePresiónCip,
  Ind090SustituciónOReemplazoDeCompresorDeAirePorUnoMásEficiente,
  Ind090anexoiiInformeJustificativoDeLaDemandaDeAire,
  Ind110RecuperaciónDeCalorDeUnCompresorParaUsoDeCalefacción,
  Ind120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas,
  Ind140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia,
  Ind140anexoiiValoresDeReferenciaDeLaFórmula,
  Ind140anexoiiiInformeJustificativoDeLaCentralFrigorífica,
  Ind150CentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta,
  Ind150anexoiiValoresDeReferenciaDeLaFórmula,
  Ind150anexoiiiInformeJustificativoDeLaCentralFrigorífica,
  Ind160UnidadCondensadoraDeAltaEficiencia,
  Ind160anexoiiValoresDeReferenciaDeLaFórmula,
  Ind160anexoiiiInformeJustificativoDeLaCentralFrigorífica,
  Ind170SustituciónDeMotoresEléctricosDeInducción,
  Ind180MejoraDeEficienciaOSustituciónDeIntercambiadorEsDeCalorParaLaReducciónDeLaResistividadTérmicaEnSistemasIndustriales,
  Ind190DivisiónDeLíneasDeEvaporaciónEnInstalaciónFrigoríficaCentralizada,
  Ind190anexoiiValoresDeReferenciaDeLaFormula,
  Ind190anexoiiiInformeJustificativoDeLaCentralFrigorífica,
  Ind200ImplantaciónDeSistemasEconomizadoresOMultietapaEnInstalaciónFrigoríficaCentralizadaOCompacta,
  Ind200anexoiiValoresDeReferenciaDeLaFórmula,
  Ind210ReducciónDeLaPresiónDeCondensaciónEnInstalaciónFrigoríficaCentralizadaOCompactaPorCambioATecnologíaMásEficiente,
  Ind210anexoiiValoresDeReferenciaDeLaFórmula,
  Ind210anexoiiiInformeJustificativoDeLaCentralFrigorífica,
  Ind220AumentoDeLaPresiónDeEvaporaciónPorCambioATecnologíaMásEficienteEnUnaInstalaciónFrigoríficaCentralizadaOCompacta,
  Ind220anexoiiValoresDeReferenciaDeLaFórmula,
  Ind220anexoiiiInformeJustificativoDeLaCentralFrigorífica,
  Ind230RecuperaciónDeCalorDesdeProcesosExotérmicosAOtrosProcesosEndotérmicosDeLaMismaPlanta,
  Ind230anexoiiInformeJustificativoDeLosEquiposQueCeden,
  Ind240ImplantaciónDeVariadorDeVelocidad,
  Ind250SustituciónTotalOParcialDeLaInstalaciónTérmicaPorTecnologíaSolarTérmica,
  Ind260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai,
  Ind260anexoiiDeclaraciónResponsablePorLaEmpresa,
  Ind270SustituciónDeTransporteNeumáticoDeSólidosPorSistemaDeTransporteMecánico,
  Ind280SustituciónDeBombaPorOtraMásEficiente,
  Ind280anexoiiCálculoDelRendimientoTotalDeLaBomba,
  Ind290RecuperaciónDeCalorEnCircuitoFrigorífico,
  Res010RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaMayorDel25PorCiento,
  Res010anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Res011RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaMayorDel25PorCientoCanarias,
  Res011anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Res020RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaInferiorOIgualAl25PorCientoDeLaEnvolventeTérmicaFinal,
  Res020anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Res021RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosDeViviendasConSuperficieAfectadaInferiorOIgualAl25PorCientoDeLaEnvolventeTérmicaFinalCanarias,
  Res021anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Res030NuevaImplantaciónSustituciónOAmpliaciónDeInstalaciónTérmicaEnUnEdificioYPiscinaConTecnologíaSolarTérmica,
  Res040SistemaDeAutomatizaciónYControlParaViviendasYEdificiosBacs1,
  Res040anexoii1TablaDeFactoresDeEficienciaParaEdificios,
  Res040anexoiiiDeclaraciónResponsableDeLaEvaluaciónDeLa,
  Res050AdquisiciónDeFrigoríficosDeAltaEficiencia,
  Res050anexoiiTablasConValoresDeReferenciaConsumosDe,
  Res051AdquisiciónDeFrigoríficocongeladorDeAltaEficiencia,
  Res051anexoiiTablasConValoresDeReferenciaConsumosDe,
  Res052AdquisiciónDeCongeladorDeAltaEficiencia,
  Res052anexoiiTablasConValoresDeReferenciaConsumosDe,
  Res053AdquisiciónDeLavadorasDeAltaEficiencia,
  Res053anexoiiTablasConValoresDeReferenciaConsumosDe,
  Res054AdquisiciónDeLavavajillasDeAltaEficiencia,
  Res054anexoiiTablasConValoresDeReferenciaConsumosDe,
  Res060SustituciónDeCalderaDeCombustiónPorUnaBombaDeCalorDeAccionamientoEléctrico,
  Res060anexoiiCasosDondeLaCalderaDeCombustiónSeMantiene,
  Res060anexoiiiEquivalenciasClimasCteYZonasClimáticas,
  Res060anexoivFórmulasParaObtenerLosCoeficientesDe,
  Res060anexovDocumentaciónTécnica,
  Res060anexoviCondicionesConsideradasEnAcs,
  Res070RenovaciónOSustituciónDeVentanasEnEdificiosDeViviendas,
  Res070anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Res071RenovaciónOSustituciónDeVentanasEnEdificiosDeViviendasCanarias,
  Res071anexoiiValoresDeCoeficienteGSegúnZonaClimática,
  Res080RehabilitaciónProfundaDeEdificiosDeViviendas,
  Res090HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaA3OA4,
  Res090anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res090anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia,
  Res091HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaB3OB4,
  Res091anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res091anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia,
  Res092HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaC1C2C3OC4,
  Res092anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res092anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia,
  Res093HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaD1D2OD3,
  Res093anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res093anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia,
  Res094HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaE1,
  Res094anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res094anexoiiiTablaDeCoeficientes1DeCoberturaPorBivalencia,
  Res095HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosResidencialesUbicadosEnLaZonaClimáticaA3OA4,
  Res095anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res095anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia,
  Res096anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res096anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia,
  Res097anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res097anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia,
  Res098anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res098anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia,
  Res099anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Res099anexoiiiTablaDeCoeficientesDeCoberturaPorBivalencia,
  Res210anexoiiRendimientoDeCalderaSustituida,
  Res220anexoiiFactoresParaElCálculoDelAhorroDeEnergía,
  Res230anexoiiFactoresParaElCálculoDelAhorroDeEnergía,
  Ter010RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosTerciariosExistentesConSuperficieAfectadaMayorDel25PorCiento,
  Ter010anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Ter011RehabilitaciónDeLaEnvolventeTérmicaDeEdificiosTerciariosExistentesConSuperficieAfectadaMayorDel25PorCientoCanarias,
  Ter011anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Ter020RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosTerciariosConSuperficieAfectadaInferiorOIgualDel25PorCientoDeLaEnvolventeTérmicaFinal,
  Ter020anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Ter021RehabilitaciónDeLaParteOpacaDeLaEnvolventeTérmicaDeEdificiosTerciariosConSuperficieAfectadaInferiorOIgualDel25PorCientoDeLaEnvolventeTérmicaFinalCanarias,
  Ter021anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Ter030SustituciónDelSistemaDeIluminaciónPorSistemaConFuentesLuminosasYOLuminariasTipoLed,
  Ter030anexoiiTiempoAnualDeFuncionamientoDelSistemaDe,
  Ter040SustituciónDeGeneradorDeClimatizaciónPorBombaDeCalorDeAccionamientoEléctrico,
  Ter040anexoiiCálculoDelRendimientoEstacionalDeEquipos,
  Ter040anexoiiiEquivalenciasClimasCteYZonasClimáticas,
  Ter040anexoivFórmulasParaObtenerLosCoeficientesDe,
  Ter040anexoixCondicionesDeTemperaturaExteriorMedia,
  Ter040anexovDocumentaciónTécnica,
  Ter040anexoviCálculoDeLaDemandaDeAcs,
  Ter040anexoviiCondicionesConsideradasEnAcs,
  Ter040anexoviiiCondicionesGeneralesParaCálculoDel,
  Ter050SistemaDeAutomatizaciónYControlParaEdificiosDelSectorTerciarioBacs1,
  Ter050anexoii1TablaDeFactoresDeEficienciaParaEdificiosNo,
  Ter050anexoiiiDeclaraciónResponsableDeLaEvaluaciónDeLa,
  Ter060RenovaciónOSustituciónDeVentanasEnEdificiosTerciariosExistentes,
  Ter060anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Ter061RenovaciónOSustituciónDeVentanasEnEdificiosExistentesCanarias,
  Ter061anexoiiValoresDelCoeficienteGSegúnZonaClimática,
  Ter070NuevaImplantaciónSustituciónOAmpliaciónDeInstalaciónTérmicaEnUnEdificioYPiscinaConTecnologíaSolarTérmica,
  Ter080RehabilitaciónProfundaDeUnEdificioTerciarioExistente,
  Ter090SustituciónDelRefrigeranteDeUnaInstalaciónFrigorífica,
  Ter090anexoiiTablas,
  Ter090anexoiiiNotaInformativaAcercaDeLaSustituciónDe,
  Ter100SustituciónDeCalderaDeCombustiónExistentePorBombaDeCalorDeAccionamientoEléctrico,
  Ter100anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter100anexoiiiDocumentaciónTécnica,
  Ter100anexoivCondicionesConsideradasEnAcs,
  Ter100anexovCálculoDeLaDemandaDeAcs,
  Ter100anexoviCondicionesGeneralesParaCálculoDeLa,
  Ter100anexoviiCondicionesDeTemperaturaExteriorMedia,
  Ter100anexoviiiRendimientoDeCalderaSustituida,
  Ter110SustituciónDeCompresorParaInstalaciónFrigoríficaODeClimatización,
  Ter110anexoiiValoresDeReferenciaDeLaFórmula,
  Ter120SustituciónDeQuemadorModulanteDeCalderaDeCombustiónDeGas,
  Ter140ReformaSustituciónONuevaInstalaciónDePlantaEnfriadoraDeProcesosDeAltaEficiencia,
  Ter140anexoiiValoresDeReferenciaDeLaFórmula,
  Ter140anexoiiiInformeJustificativoDeLaCentralFrigorífica,
  Ter150ReformaSustituciónONuevaInstalaciónDeCentralFrigoríficaDeAltaEficienciaConSistemasDeRefrigeraciónDirecta,
  Ter150anexoiiValoresDeReferenciaDeLaFórmula,
  Ter150anexoiiiInformeJustificativoDeLaCentralFrigorífica,
  Ter160SustituciónReformaONuevaInstalaciónDeUnaUnidadCondensadoraDeAltaEficiencia,
  Ter160anexoiiValoresDeReferenciaDeLaFórmula,
  Ter160anexoiiiInformeJustificativoDeLaCentralFrigorífica,
  Ter170HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaA3OA4,
  Ter170anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter170anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter170anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia,
  Ter171HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaB3OB4,
  Ter171anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter171anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter171anexoivTablaDeCoeficientes1DeCoberturaPor,
  Ter172HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaC1C2C3OC4,
  Ter172anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter172anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter172anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia,
  Ter173HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaD1D2OD3,
  Ter173anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter173anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter173anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia,
  Ter174HibridaciónEnModoParaleloDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaE1,
  Ter174anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter174anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter174anexoivTablaDeCoeficientes1DeCoberturaPorBivalencia,
  Ter175HibridaciónEnModoAlternativoDeCalderaDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaA3OA4,
  Ter175anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter175anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter175anexoivTablaDeCoeficientesDeCoberturaPorBivalencia,
  Ter176HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaB3OB4,
  Ter176anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter176anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter176anexoivTablaDeCoeficientesDeCoberturaPorBivalencia,
  Ter177HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaC1C2C3OC4,
  Ter177anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter177anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter177anexoivTablaDeCoeficientesDeCoberturaPorBivalencia,
  Ter178HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaD1D2OD3,
  Ter178anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter178anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter178anexoivTablaDeCoeficientesDeCoberturaPorBivalencia,
  Ter179HibridaciónEnModoAlternativoDeCalderaSDeCombustiónConBombaDeCalorDeAccionamientoEléctricoEnEdificiosNoResidencialesUbicadosEnLaZonaClimáticaE1,
  Ter179anexoiiFórmulasParaObtenerLosCoeficientesDe,
  Ter179anexoiiiCondicionesGeneralesParaCálculoDeLa,
  Ter179anexoivTablaDeCoeficientesDeCoberturaPorBivalencia,
  Ter180SustituciónDelSistemaDeIluminaciónVialAmbiental,
  Ter190ReformadoDeAparatosDeRefrigeraciónParaAlimentosYBebidasDeVentaDirecta,
  Ter190anexoiiCoeficientesDeAhorroC,
  Ter200SustituciónDeAparatoDeRefrigeraciónConFunciónDeVentaDirecta,
  Ter210SustituciónDeCalderasIndividualesColectivaEnEdificioTerciarioPorConexiónAUnaRedDeCalor,
  Ter210anexoiiRendimientoDeCalderaSustituida,
  Ter220SustituciónDeUnSistemaDeVentilaciónExistenteNaturalOMecánicaPorUnSistemaDeVentilaciónMecánicaConRecuperaciónDeCalorDeAltaEficienciaEnEdificiosNoResidenciales,
  Ter220anexoiiFactoresParaElCálculoDelAhorroDeEnergía,
  Ter240ImplantaciónDeVariadorDeVelocidad,
  Ter260SustituciónDeUnSistemaDeAlimentaciónIninterrumpidaSai,
  Ter260anexoiiDeclaraciónResponsablePorLaEmpresa,
  Ter280SustituciónDeBombaPorOtraMásEficiente,
  Ter280anexoiiCálculoDelRendimientoTotalDeLaBomba,
  Tra010anexoiDeclaraciónResponsableFormalizadaPorEl,
  Tra010anexoiiAhorroEnergéticoPorSustituciónDeNeumático,
  Tra010anexoiiiKilometrosRealizadosSegúnLaTipologíaDel,
  Tra020anexoiiRequerimientosTécnicosDeLaSoluciónTelemática,
  Tra030VehículoCompartidoEnTrayectosDeLargoRecorrido,
  Tra030anexoiiRequisitosParaLaAplicaciónDeLaFicha,
  Tra030anexoiiiCriteriosAntifraudeParaLaCorrecta,
  Tra040MovilidadColaborativaUrbanaYMetropolitana,
  Tra040anexoiDeclaraciónResponsableFormalizadaPorEl,
  Tra040anexoiiRequisitosParaLaAplicaciónDeLaFicha,
  Tra040anexoiiiCriteriosAntifraudeParaLaCorrecta,
  Tra050SustituciónDeVehículoDeCombustiónPorUnVehículoEléctricoPuro,
  Tra050anexoiDeclaraciónResponsableFormalizadaPorEl,
  Tra050anexoiiMétodosParaObtenerLosConsumosDeVehículos,
  Tra050anexoiiiKilometrosRealizadosSegúnLaTipologíaDel,
  Cer1001TérminoDeFacturaciónDeEnergíaActivaDelPvpc20td,
  Cer1739PrecioDeLaEnergíaExcedentariaDelAutoconsumo,
  Acaf000AnálisisFinanciero,
  Acpvpc00PreciosPvpc,
  Afc020AutoconsumoColectivoConExcedentesYConCompensaciónConectadaEnRedInterior,
  Aif030AnálisisDeOfertaDeAutoconsumo,
  Aif040GeneracionFotovoltaica,
  Bt040401InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónBásico,
  Bt040402InstalaciónEléctricaDeViviendaUnifamiliarConGradoDeElectrificaciónElevado,
  Bt100PrevisiónDeCargasParaSuministrosEnBajaTensión,
  Bt220ProtecciónContraSobreintensidades,
  Bt240ProtecciónContraContactosIndirectos,
  Bt400InstalacionesGeneradorasDeBajaTensión,
  Bt520InfraestructuraParaLaRecargaDeVehículosEléctricos,
  Btx030BateríaDeCondensadores,
  Btx040FiltroDeArmónicos,
  Btx047InstalaciónDeComunicaciónDeSaiLegrand,
  Btx060SistemaDeAlimentaciónIninterrumpidaSai,
};

export default componentsMap;
