import Codigo456NombreSeparadoPorMayusculasSinEspacios from './docs/AAA/AAA/Codigo456NombreSeparadoPorMayusculasSinEspacios.jsx';
import Codigo123NombreSeparadoPorMayusculasSinEspacios from './docs/AAA/AAA/Codigo123NombreSeparadoPorMayusculasSinEspacios.jsx';
import Cer1739PrecioDeLaEnergíaExcedentariaDelAutoconsumo from './docs/CONTRATOS_DE_ENERGÍA/Mercado_regulado/Cer1739PrecioDeLaEnergíaExcedentariaDelAutoconsumo.jsx';
import Cer1001TérminoDeFacturaciónDeEnergíaActivaDelPvpc20td from './docs/CONTRATOS_DE_ENERGÍA/Mercado_regulado/Cer1001TérminoDeFacturaciónDeEnergíaActivaDelPvpc20td.jsx';
import Aif030AnálisisDeOfertaDeAutoconsumo from './docs/CONTRATOS_DE_ENERGÍA/Mercado_libre/Aif030AnálisisDeOfertaDeAutoconsumo.jsx';

const componentsMap = {
  Codigo456NombreSeparadoPorMayusculasSinEspacios,
  Codigo123NombreSeparadoPorMayusculasSinEspacios,
  Cer1739PrecioDeLaEnergíaExcedentariaDelAutoconsumo,
  Cer1001TérminoDeFacturaciónDeEnergíaActivaDelPvpc20td,
  Aif030AnálisisDeOfertaDeAutoconsumo,
};

export default componentsMap;
