from fastapi import APIRouter
router = APIRouter()
from .Agr010anexoiiiDeclaraciónResponsableDelValorDel import router as Agr010anexoiiiDeclaraciónResponsableDelValorDel_router
router.include_router(Agr010anexoiiiDeclaraciónResponsableDelValorDel_router, prefix='/Agr010anexoiiiDeclaraciónResponsableDelValorDel', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Agrario'])
from .Agr010PantallasTérmicasEnInvernaderos import router as Agr010PantallasTérmicasEnInvernaderos_router
router.include_router(Agr010PantallasTérmicasEnInvernaderos_router, prefix='/Agr010PantallasTérmicasEnInvernaderos', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Agrario'])
from .Agr020RecuperaciónDelCalorDelProcesoDePreenfriamientoDeLaLecheParaUsosTérmicosEnLaExplotaciónGanadera import router as Agr020RecuperaciónDelCalorDelProcesoDePreenfriamientoDeLaLecheParaUsosTérmicosEnLaExplotaciónGanadera_router
router.include_router(Agr020RecuperaciónDelCalorDelProcesoDePreenfriamientoDeLaLecheParaUsosTérmicosEnLaExplotaciónGanadera_router, prefix='/Agr020RecuperaciónDelCalorDelProcesoDePreenfriamientoDeLaLecheParaUsosTérmicosEnLaExplotaciónGanadera', tags=['root - CERTIFICADOS_DE_AHORRO_ENERGÉTICO_CAE - Agrario'])
